/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Cymbal.glb -o src/components/Cymbal.jsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Cymbal(props) {
  const { nodes, materials } = useGLTF("/models/Cymbal_ao.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.phong1SG} />
    </group>
  );
}

useGLTF.preload("/models/Cymbal.glb");
