/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Drum.glb -o src/components/Drum.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Drum({ color, ...props }) {
  const { nodes, materials } = useGLTF("/models/Drum_ao.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Drum_Circle002_1.geometry}>
        <meshStandardMaterial aoMap={materials.F44336.aoMap} color={color} />
      </mesh>

      <mesh
        geometry={nodes.Drum_Circle002_1_1.geometry}
        material={materials.DD9944}
      />
      <mesh
        geometry={nodes.Drum_Circle002_1_2.geometry}
        material={materials["455A64"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Drum.glb");
