/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Drum stick.glb -o src/components/DrumStick.jsx
*/

import { useGLTF } from "@react-three/drei";
import { DefaultXRInputSourceRayPointer } from "@react-three/xr";
import React from "react";
import { degToRad } from "three/src/math/MathUtils.js";

export function DrumStick(props) {
  const { nodes, materials } = useGLTF("/models/Drum stick.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation-x={degToRad(30)}>
        <DefaultXRInputSourceRayPointer makeDefault minDistance={0.2} />
      </group>
      <group rotation-x={-degToRad(60)} scale={0.03}>
        <group position-y={-2.8}>
          <mesh
            geometry={nodes.Drumstick_Circle007.geometry}
            material={materials.DD9944}
          />
        </group>
      </group>
    </group>
  );
}
