/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Drum stick.glb -o src/components/DrumStick.jsx
*/

import { useGLTF } from "@react-three/drei";
import { DefaultXRInputSourceRayPointer } from "@react-three/xr";
import React, { useRef } from "react";
import { Quaternion, Vector3 } from "three";
import { degToRad } from "three/src/math/MathUtils.js";
import { useSong } from "../hooks/useSong";

export function DrumStick(props) {
  const { nodes, materials } = useGLTF("/models/Drum stick.glb");
  const ref = useRef();
  // const rb = useRef();

  const positionTmp = useRef(new Vector3());
  const quaternionTmp = useRef(new Quaternion());

  // useFrame(() => {
  //   if (ref.current && rb.current) {
  //     ref.current.getWorldPosition(positionTmp.current);
  //     ref.current.getWorldQuaternion(quaternionTmp.current);

  //     rb.current.setTranslation(positionTmp.current);
  //     rb.current.setRotation(quaternionTmp.current);
  //   }
  // });
  const playNote = useSong((state) => state.playNote);

  return (
    <group {...props} dispose={null}>
      <group rotation-x={degToRad(30)}>
        <DefaultXRInputSourceRayPointer makeDefault minDistance={0.2} />
      </group>
      <group rotation-x={-degToRad(60)} scale={0.03}>
        <group position-y={-2.8}>
          <mesh
            geometry={nodes.Drumstick_Circle007.geometry}
            material={materials.DD9944}
          />
        </group>
      </group>
    </group>
  );
}
